config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact_us', to: 'pages#contact_us'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def about; end

  def contact_us; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bcrubyapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body class="d-flex flex-column min-vh-100">
  <% flash.each do |key, message| %>
    <div class="flash <%= key %>"><%= message %></div>
  <% end %>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to 'Home', root_path, class: "nav-link active" %></li>
          <li class="nav-item"><%= link_to 'About', about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Contact', contact_us_path, class: "nav-link" %></li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Log out', destroy_user_session_path, data: { 'turbo-method': :delete }, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to 'Log in', new_user_session_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container flex-grow-1">
    <%= yield %>
  </div>

  <footer class="small text-muted">
    <div class="container">
      <hr>
      <center>
        <p>&copy; 2025 One Month</p>
      </center>
    </div>
  </footer>
</body>

</html>

app/views/pages/about.html.erb
<div class="jumbotron jumbotron-home">
  <div class="container">
    <h1>About us</h1>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit.
      Accusantium repellat suscipit doloremque illo exercitationem
      itaque placeat inventore esse, quam ipsum ipsam minus doloribus id
      iusto possimus eos odio molestias quos?
    </p>
  </div>
</div>

app/views/pages/contact_us.html.erb
<div class="container">
  <h1>Welcome to Contact Us page</h1>
</div>

app/views/pages/home.html.erb
  <% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
      <div class="container">
        <h1>Welcome back <%= current_user.email %></h1>
      </div>
    </div>
  <% else %>
    <div class="jumbotron jumbotron-home">
      <div class="container">
        <h1>Welcome</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Accusantium repellat suscipit doloremque illo exercitationem
          itaque placeat inventore esse, quam ipsum ipsam minus doloribus id
          iusto possimus eos odio molestias quos?
        </p>
      </div>
    </div>

  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit.
          Voluptate sit natus facilis earum! Quas totam itaque est corrupti
          ipsa quod! Harum amet soluta mollitia impedit placeat, nihil quisquam optio modi.
        </p>
        <p><%= link_to  "View in details", "#", class:"btn btn-secondary"%></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit.
          Voluptate sit natus facilis earum! Quas totam itaque est corrupti
          ipsa quod! Harum amet soluta mollitia impedit placeat, nihil quisquam optio modi.
        </p>
        <p><%= link_to  "View in details", "#", class:"btn btn-secondary"%></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit.
          Voluptate sit natus facilis earum! Quas totam itaque est corrupti
          ipsa quod! Harum amet soluta mollitia impedit placeat, nihil quisquam optio modi.
        </p>
        <p><%= link_to  "View in details", "#", class:"btn btn-secondary"%></p>
      </div>
    </div>
  </div>
  <% end %>